"""Game session

Revision ID: 57798ee22cbc
Revises: b6690d163bef
Create Date: 2025-12-14 23:20:09.954216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57798ee22cbc'
down_revision: Union[str, Sequence[str], None] = 'b6690d163bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('game_poster', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'game_poster')
    # ### end Alembic commands ###
